In [7]:
import numpy as np
import pandas as pd
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [13]:
dataset = np.loadtxt('D:\\docu\\Book\\ML\\python_ml_bundle_7books\\xgboost_with_python\\code\\chapter_04\\pima-indians-diabetes.csv', delimiter = ',')
# pd.DataFrame(dataset)

        0      1     2     3      4     5      6     7    8
0     6.0  148.0  72.0  35.0    0.0  33.6  0.627  50.0  1.0
1     1.0   85.0  66.0  29.0    0.0  26.6  0.351  31.0  0.0
2     8.0  183.0  64.0   0.0    0.0  23.3  0.672  32.0  1.0
3     1.0   89.0  66.0  23.0   94.0  28.1  0.167  21.0  0.0
4     0.0  137.0  40.0  35.0  168.0  43.1  2.288  33.0  1.0
..    ...    ...   ...   ...    ...   ...    ...   ...  ...
763  10.0  101.0  76.0  48.0  180.0  32.9  0.171  63.0  0.0
764   2.0  122.0  70.0  27.0    0.0  36.8  0.340  27.0  0.0
765   5.0  121.0  72.0  23.0  112.0  26.2  0.245  30.0  0.0
766   1.0  126.0  60.0   0.0    0.0  30.1  0.349  47.0  1.0
767   1.0   93.0  70.0  31.0    0.0  30.4  0.315  23.0  0.0

[768 rows x 9 columns]

In [14]:
X = dataset[:, :-1]
Y = dataset[:, -1]

In [16]:
seed = 7
test_size = 0.33
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=test_size, random_state=seed)

In [17]:
model = XGBClassifier(use_label_encoder=False)
model.fit(X_train, y_train)
print(model)

[12:03:29] WARNING: ..\src\learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, enable_categorical=False,
              gamma=0, gpu_id=-1, importance_type=None,
              interaction_constraints='', learning_rate=0.300000012,
              max_delta_step=0, max_depth=6, min_child_weight=1, missing=nan,
              monotone_constraints='()', n_estimators=100, n_jobs=12,
              num_parallel_tree=1, predictor='auto', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, subsample=1,
              tree_method='exact', validate_parameters=1, verbosity=None)

D:\develop\Anaconda3\lib\site-packages\xgboost\sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)

In [19]:
prediction = model.predict(X_test)
# evaluate predictions
accuracy = accuracy_score(y_test, prediction)
print("Accuracy: %.2f%%" % (accuracy * 100.0))

Accuracy: 74.02%